apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nexus-volume
  labels:
    type: local
spec: 
  capacity: 
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/app-project/nexus/volume"
