apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
spec:
  type: NodePort
  ports:
    - nodePort: 31000        
      port: 8080
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: nexus
